					;-*- mode: lisp; -*-
;;messagebox type flags
(defconstant +mb-ok+ #x000000)
(defconstant +mb-okcancel+ #x000001)
(defconstant +mb-abortretryignore+ #x000002)
(defconstant +mb-yesnocancel+ #x000003)
(defconstant +mb-yesno+ #x000004)
(defconstant +mb-retrycancel+ #x000005)
(defconstant +mb-iconhand+ #x000010)
(defconstant +mb-iconquestion+ #x000020)
(defconstant +mb-iconexclamation+ #x000030)
(defconstant +mb-iconasterisk+ #x000040)
(defconstant +mb-usericon+ #x000080)
(defconstant +mb-iconwarning+ +mb-iconexclamation+)
(defconstant +mb-iconerror+ +mb-iconhand+)
(defconstant +mb-iconinformation+ +mb-iconasterisk+)
(defconstant +mb-iconstop+ +mb-iconhand+)
(defconstant +mb-defbutton1+ #x000000)
(defconstant +mb-defbutton2+ #x000100)
(defconstant +mb-defbutton3+ #x000200)
(defconstant +mb-defbutton4+ #x000300)
(defconstant +mb-applmodal+ #x000000)
(defconstant +mb-systemmodal+ #x001000)
(defconstant +mb-taskmodal+ #x002000)
(defconstant +mb-help+ #x004000)
(defconstant +mb-nofocus+ #x008000)
(defconstant +mb-setforeground+ #x010000)
(defconstant +mb-default-desktop-only #x020000)
(defconstant +mb-topmost+ #x040000)
(defconstant +mb-right+ #x080000)
(defconstant +mb-rtlreading+ #x100000)
(defconstant +mb-service-notification #x200000)

;;conventional dialog box and message box command ids
(defconstant +idok+ 1)
(defconstant +idcancel+ 2)
(defconstant +idabort+ 3)
(defconstant +idretry+ 4)
(defconstant +idignore+ 5)
(defconstant +idyes+ 6)
(defconstant +idno+ 7)
(defconstant +idclose+ 8)
(defconstant +idhelp+ 9)

;;class styles
(defconstant +cs-vredraw+ #x00001)
(defconstant +cs-hredraw+ #x00002)
(defconstant +cs-keycvtwindow+ #x00004)
(defconstant +cs-dblclks+ #x00008)
(defconstant +cs-owndc+ #x00020)
(defconstant +cs-classdc+ #x00040)
(defconstant +cs-parentdc+ #x00080)
(defconstant +cs-nokeycvt+ #x00100)
(defconstant +cs-savebits+ #x00800)
(defconstant +cs-noclose+ #x00200)
(defconstant +cs-bytealignclient+ #x01000)
(defconstant +cs-bytealignwindow+ #x02000)
(defconstant +cs-publicclass+ #x04000)
(defconstant +cs-globalclass+ +cs-publicclass+)
(defconstant +cs-ime+ #x10000)

;;windows styles
(defconstant +ws-overlapped+ #x000000000)
(defconstant +ws-iconicpopup+ #x0c0000000)
(defconstant +ws-popup+ #x080000000)
(defconstant +ws-child+ #x040000000)
(defconstant +ws-minimize+ #x020000000)
(defconstant +ws-visible+ #x010000000)
(defconstant +ws-disabled+ #x008000000)
(defconstant +ws-clipsiblings+ #x004000000)
(defconstant +ws-clipchildren+ #x002000000)
(defconstant +ws-maximize+ #x001000000)
(defconstant +ws-caption+ #x000c00000)
(defconstant +ws-border+ #x000800000)
(defconstant +ws-dlgframe+ #x000400000)
(defconstant +ws-vscroll+ #x000200000)
(defconstant +ws-hscroll+ #x000100000)
(defconstant +ws-sysmenu+ #x000080000)
(defconstant +ws-thickframe+ #x000040000)
(defconstant +ws-hredraw+ #x000020000)
(defconstant +ws-vredraw+ #x000010000)
(defconstant +ws-group+ #x000020000)
(defconstant +ws-tabstop+ #x000010000)
(defconstant +ws-minimizebox+ #x000020000)
(defconstant +ws-maximizebox+ #x000010000)

;;common window styles
(defconstant +ws-overlappedwindow+ (+ +ws-overlapped+ +ws-caption+ +ws-sysmenu+ +ws-thickframe+ +ws-minimizebox+ +ws-maximizebox+))
(defconstant +ws-popupwindow+ (+ +ws-popup+ +ws-border+ +ws-sysmenu+))
(defconstant +ws-childwindow+ +ws-child+)
(defconstant +ws-tiledwindow+ +ws-overlappedwindow+)
(defconstant +ws-tiled+ +ws-overlapped+)
(defconstant +ws-iconic+ +ws-minimize+)
(defconstant +ws-sizebox+ +ws-thickframe+)

;;extended window styles
(defconstant +ws-ex-dlgmodalframe+ #x00001)
(defconstant +ws-ex-dragobject+ #x00002)
(defconstant +ws-ex-noparentnotify+ #x00004)
(defconstant +ws-ex-topmost+ #x00008)
(defconstant +ws-ex-acceptfiles+ #x00010)
(defconstant +ws-ex-transparent+ #x00020)
(defconstant +ws-ex-mdichild+ #x00040)
(defconstant +ws-ex-toolwindow+ #x00080)
(defconstant +ws-ex-windowedge+ #x00100)
(defconstant +ws-ex-clientedge+ #x00200)
(defconstant +ws-ex-contexthelp+ #x00400)
(defconstant +ws-ex-right+ #x01000)
(defconstant +ws-ex-left+ #x00000)
(defconstant +ws-ex-rtlreading+ #x02000)
(defconstant +ws-ex-ltrreading+ #x00000)
(defconstant +ws-ex-leftscrollbar+ #x04000)
(defconstant +ws-ex-rightscrollbar+ #x00000)
(defconstant +ws-ex-controlparent+ #x10000)
(defconstant +ws-ex-staticedge+ #x20000)
(defconstant +ws-ex-appwindow+ #x40000)
(defconstant +ws-ex-layered+ #x80000)
(defconstant +ws-ex-overlappedwindow+ (+ +ws-ex-windowedge+ +ws-ex-clientedge+))
(defconstant +ws-ex-palettewindow+ (+ +ws-ex-windowedge+ +ws-ex-toolwindow+ +ws-ex-topmost+))

;;mdi client style bits
(defconstant +mdis-allchildstyles+ 1)

;;special createwindow position value
(defconstant +cw-usedefault+ #x80000000)

;;predefined window handle
(defconstant +hwnd-desktop+ 0)

;;showwindow commands
(defconstant +sw-hide+ 0)
(defconstant +sw-shownormal+ 1)
(defconstant +sw-normal+ 1)
(defconstant +sw-showminimized+ 2)
(defconstant +sw-showmaximized+ 3)
(defconstant +sw-maximize+ 3)
(defconstant +sw-shownoactivate+ 4)
(defconstant +sw-show+ 5)
(defconstant +sw-minimize+ 6)
(defconstant +sw-showminnoactive+ 7)
(defconstant +sw-showna+ 8)
(defconstant +sw-restore+ 9)
(defconstant +sw-showdefault+ 10)

;;setwindowpos flags
(defconstant +swp-nosize+ #x0001)
(defconstant +swp-nomove+ #x0002)
(defconstant +swp-nozorder+ #x0004)
(defconstant +swp-noredraw+ #x0008)
(defconstant +swp-noactivate+ #x0010)
(defconstant +swp-drawframe+ #x0020)
(defconstant +swp-showwindow+ #x0040)
(defconstant +swp-hidewindow+ #x0080)
(defconstant +swp-nocopybits+ #x0100)
(defconstant +swp-noreposition+ #x0200)
(defconstant +swp-defererase+ #x2000)
(defconstant +swp-asyncwindowpos+ #x4000)

;;setwindowpos special handle values
(defconstant +hwnd-top+ 0)
(defconstant +hwnd-bottom+ 1)
(defconstant +hwnd-topmost+ -1)
(defconstant +hwnd-notopmost+ -2)

;;getwindow flags
(defconstant +gw-hwndfirst+ 0)
(defconstant +gw-hwndlast+ 1)
(defconstant +gw-hwndnext+ 2)
(defconstant +gw-hwndprev+ 3)
(defconstant +gw-owner+ 4)
(defconstant +gw-child+ 5)

;;redrawwindow flags
(defconstant +rdw-invalidate+ #x0001)
(defconstant +rdw-internalpaint+ #x0002)
(defconstant +rdw-erase+ #x0004)
(defconstant +rdw-validate+ #x0008)
(defconstant +rdw-nointernalpaint+ #x0010)
(defconstant +rdw-noerase+ #x0020)
(defconstant +rdw-nochildren+ #x0040)
(defconstant +rdw-allchildren+ #x0080)
(defconstant +rdw-updatenow+ #x0100)
(defconstant +rdw-erasenow+ #x0200)
(defconstant +rdw-frame+ #x0400)
(defconstant +rdw-noframe+ #x0800)

;;peekmessage options
(defconstant +pm-noremove+ #x0000)
(defconstant +pm-remove+ #x0001)
(defconstant +pm-noyield+ #x0002)

;;window state messages
(defconstant +wm-state+ #x0000)
(defconstant +wm-null+ #x0000)
(defconstant +wm-create+ #x0001)
(defconstant +wm-destroy+ #x0002)
(defconstant +wm-move+ #x0003)
(defconstant +wm-size+ #x0005)
(defconstant +wm-activate+ #x0006)
(defconstant +wm-setfocus+ #x0007)
(defconstant +wm-killfocus+ #x0008)
(defconstant +wm-enable+ #x000a)
(defconstant +wm-setredraw+ #x000b)
(defconstant +wm-settext+ #x000c)
(defconstant +wm-gettext+ #x000d)
(defconstant +wm-gettextlength+ #x000e)
(defconstant +wm-paint+ #x000f)
(defconstant +wm-close+ #x0010)
(defconstant +wm-queryendsession+ #x0011)
(defconstant +wm-quit+ #x0012)
(defconstant +wm-queryopen+ #x0013)
(defconstant +wm-erasebkgnd+ #x0014)
(defconstant +wm-syscolorchange+ #x0015)
(defconstant +wm-endsession+ #x0016)
(defconstant +wm-systemerror+ #x0017)
(defconstant +wm-showwindow+ #x0018)
(defconstant +wm-ctlcolor+ #x0019)
(defconstant +wm-wininichange+ #x001a)
(defconstant +wm-devmodechange+ #x001b)
(defconstant +wm-activateapp+ #x001c)
(defconstant +wm-fontchange+ #x001d)
(defconstant +wm-timechange+ #x001e)
(defconstant +wm-cancelmode+ #x001f)
(defconstant +wm-setcursor+ #x0020)
(defconstant +wm-mouseactivate+ #x0021)
(defconstant +wm-childactivate+ #x0022)
(defconstant +wm-queuesync+ #x0023)
(defconstant +wm-getminmaxinfo+ #x0024)
(defconstant +wm-painticon+ #x0026)
(defconstant +wm-iconerasebkgnd+ #x0027)
(defconstant +wm-nextdlgctl+ #x0028)
(defconstant +wm-spoolerstatus+ #x002a)
(defconstant +wm-drawitem+ #x002b)
(defconstant +wm-measureitem+ #x002c)
(defconstant +wm-deleteitem+ #x002d)
(defconstant +wm-vkeytoitem+ #x002e)
(defconstant +wm-chartoitem+ #x002f)
(defconstant +wm-setfont+ #x0030)
(defconstant +wm-getfont+ #x0031)
(defconstant +wm-sethotkey+ #x0032)
(defconstant +wm-querydragicon+ #x0037)
(defconstant +wm-compareitem+ #x0039)
(defconstant +wm-compacting+ #x0041)
(defconstant +wm-commnotify+ #x0044)
(defconstant +wm-windowposchanging+ #x0046)
(defconstant +wm-windowposchanged+ #x0047)
(defconstant +wm-power+ #x0048)
(defconstant +wm-copydata+ #x004a)
(defconstant +wm-canceljournal+ #x004b)
(defconstant +wm-notify+ #x004e)
(defconstant +wm-inputlangchangerequest+ #x0050)
(defconstant +wm-inputlangchange+ #x0051)
(defconstant +wm-tcard+ #x0052)
(defconstant +wm-help+ #x0053)
(defconstant +wm-userchanged+ #x0054)
(defconstant +wm-notifyformat+ #x0055)
(defconstant +wm-contextmenu+ #x007b)
(defconstant +wm-stylechanging+ #x007c)
(defconstant +wm-stylechanged+ #x007d)
(defconstant +wm-displaychange+ #x007e)
(defconstant +wm-geticon+ #x007f)
(defconstant +wm-seticon+ #x0080)
(defconstant +wm-nccreate+ #x0081)
(defconstant +wm-ncdestroy+ #x0082)
(defconstant +wm-nccalcsize+ #x0083)
(defconstant +wm-nchittest+ #x0084)
(defconstant +wm-ncpaint+ #x0085)
(defconstant +wm-ncactivate+ #x0086)
(defconstant +wm-getdlgcode+ #x0087)
(defconstant +wm-ncmousemove+ #x00a0)
(defconstant +wm-nclbuttondown+ #x00a1)
(defconstant +wm-nclbuttonup+ #x00a2)
(defconstant +wm-nclbuttondblclk+ #x00a3)
(defconstant +wm-ncrbuttondown+ #x00a4)
(defconstant +wm-ncrbuttonup+ #x00a5)
(defconstant +wm-ncrbuttondblclk+ #x00a6)
(defconstant +wm-ncmbuttondown+ #x00a7)
(defconstant +wm-ncmbuttonup+ #x00a8)
(defconstant +wm-ncmbuttondblclk+ #x00a9)
(defconstant +wm-keyfirst+ #x0100)
(defconstant +wm-keydown+ #x0100)
(defconstant +wm-keyup+ #x0101)
(defconstant +wm-char+ #x0102)
(defconstant +wm-deadchar+ #x0103)
(defconstant +wm-syskeydown+ #x0104)
(defconstant +wm-syskeyup+ #x0105)
(defconstant +wm-syschar+ #x0106)
(defconstant +wm-sysdeadchar+ #x0107)
(defconstant +wm-keylast+ #x0108)
(defconstant +wm-initdialog+ #x0110)
(defconstant +wm-command+ #x0111)
(defconstant +wm-syscommand+ #x0112)
(defconstant +wm-timer+ #x0113)
(defconstant +wm-hscroll+ #x0114)
(defconstant +wm-vscroll+ #x0115)
(defconstant +wm-initmenu+ #x0116)
(defconstant +wm-initmenupopup+ #x0117)
(defconstant +wm-gesture+ #x0119)
(defconstant +wm-gesturenotify+ #x011a)
(defconstant +wm-menuselect+ #x011f)
(defconstant +wm-menuchar+ #x0120)
(defconstant +wm-enteridle+ #x0121)
(defconstant +wm-menurbuttonup+ #x0122)
(defconstant +wm-menudrag+ #x0123)
(defconstant +wm-menugetobject+ #x0124)
(defconstant +wm-uninitmenupopup+ #x0125)
(defconstant +wm-menucommand+ #x0126)
(defconstant +wm-ctlcolormsgbox+ #x0132)
(defconstant +wm-ctlcoloredit+ #x0133)
(defconstant +wm-ctlcolorlistbox+ #x0134)
(defconstant +wm-ctlcolorbtn+ #x0135)
(defconstant +wm-ctlcolordlg+ #x0136)
(defconstant +wm-ctlcolorscrollbar+ #x0137)
(defconstant +wm-ctlcolorstatic+ #x0138)
(defconstant +wm-mousefirst+ #x0200)
(defconstant +wm-mousemove+ #x0200)
(defconstant +wm-lbuttondown+ #x0201)
(defconstant +wm-lbuttonup+ #x0202)
(defconstant +wm-lbuttondblclk+ #x0203)
(defconstant +wm-rbuttondown+ #x0204)
(defconstant +wm-rbuttonup+ #x0205)
(defconstant +wm-rbuttondblclk+ #x0206)
(defconstant +wm-mbuttondown+ #x0207)
(defconstant +wm-mbuttonup+ #x0208)
(defconstant +wm-mbuttondblclk+ #x0209)
(defconstant +wm-mousewheel+ #x020a)
(defconstant +wm-mouselast+ #x020a)
(defconstant +wm-parentnotify+ #x0210)
(defconstant +wm-entermenuloop+ #x0211)
(defconstant +wm-exitmenuloop+ #x0212)
(defconstant +wm-nextmenu+ #x0213)
(defconstant +wm-sizing+ #x0214)
(defconstant +wm-capturechanged+ #x0215)
(defconstant +wm-moving+ #x0216)
(defconstant +wm-powerbroadcast+ #x0218)
(defconstant +wm-devicechange+ #x0219)
(defconstant +wm-mdicreate+ #x0220)
(defconstant +wm-mdidestroy+ #x0221)
(defconstant +wm-mdiactivate+ #x0222)
(defconstant +wm-mdirestore+ #x0223)
(defconstant +wm-mdinext+ #x0224)
(defconstant +wm-mdimaximize+ #x0225)
(defconstant +wm-mditile+ #x0226)
(defconstant +wm-mdicascade+ #x0227)
(defconstant +wm-mdiiconarrange+ #x0228)
(defconstant +wm-mdigetactive+ #x0229)
(defconstant +wm-mdisetmenu+ #x0230)
(defconstant +wm-entersizemove+ #x0231)
(defconstant +wm-exitsizemove+ #x0232)
(defconstant +wm-dropfiles+ #x0233)
(defconstant +wm-mdirefreshmenu+ #x0234)
(defconstant +wm-ime-setcontext+ #x0281)
(defconstant +wm-ime-notify+ #x0282)
(defconstant +wm-ime-control+ #x0283)
(defconstant +wm-ime-compositionfull+ #x0284)
(defconstant +wm-ime-select+ #x0285)
(defconstant +wm-ime-char+ #x0286)
(defconstant +wm-ime-keydown+ #x0290)
(defconstant +wm-ime-keyup+ #x0291)
(defconstant +wm-mousehover+ #x02a1)
(defconstant +wm-mouseleave+ #x02a3)
(defconstant +wm-cut+ #x0300)
(defconstant +wm-copy+ #x0301)
(defconstant +wm-paste+ #x0302)
(defconstant +wm-clear+ #x0303)
(defconstant +wm-undo+ #x0304)
(defconstant +wm-renderformat+ #x0305)
(defconstant +wm-renderallformats+ #x0306)
(defconstant +wm-destroyclipboard+ #x0307)
(defconstant +wm-drawclipboard+ #x0308)
(defconstant +wm-paintclipboard+ #x0309)
(defconstant +wm-vscrollclipboard+ #x030a)
(defconstant +wm-sizeclipboard+ #x030b)
(defconstant +wm-askcbformatname+ #x030c)
(defconstant +wm-changecbchain+ #x030d)
(defconstant +wm-hscrollclipboard+ #x030e)
(defconstant +wm-querynewpalette+ #x030f)
(defconstant +wm-paletteischanging+ #x0310)
(defconstant +wm-palettechanged+ #x0311)
(defconstant +wm-hotkey+ #x0312)
(defconstant +wm-print+ #x0317)
(defconstant +wm-printclient+ #x0318)
(defconstant +wm-handheldfirst+ #x0358)
(defconstant +wm-handheldlast+ #x035f)
(defconstant +wm-afxfirst+ #x0360)
(defconstant +wm-afxlast+ #x037f)
(defconstant +wm-penwinfirst+ #x0380)
(defconstant +wm-penwinlast+ #x038f)
(defconstant +wm-coalesce-first+ #x0390)
(defconstant +wm-coalesce-last+ #x039f)
(defconstant +wm-user+ #x0400)

;;wm-size commands
(defconstant +size-restored+ 0)
(defconstant +size-minimized+ 1)
(defconstant +size-maximized+ 2)
(defconstant +size-maxshow+ 3)
(defconstant +size-maxhide+ 4)

;;wm-activate states
(defconstant +wa-inactive+ 0)
(defconstant +wa-active+ 1)
(defconstant +wa-clickactive+ 2)

;;wm-showwindow identifiers
(defconstant +sw-parentclosing+ 1)
(defconstant +sw-otherzoom+ 2)
(defconstant +sw-parentopening+ 3)
(defconstant +sw-otherunzoom+ 4)

;;wm-mouseactivate return codes
(defconstant +ma-activate+ 1)
(defconstant +ma-activateandeat+ 2)
(defconstant +ma-noactivate+ 3)
(defconstant +ma-noactivateandeat+ 4)

;;wm-mditile flags
(defconstant +mditile-vertical+ 0)
(defconstant +mditile-horizontal+ 1)
(defconstant +mditile-skipdisabled+ 2)

;;wm-notify codes
(defconstant +nm-outofmemory+ -1)
(defconstant +nm-click+ -2)
(defconstant +nm-dblclick+ -3)
(defconstant +nm-return+ -4)
(defconstant +nm-rclick+ -5)
(defconstant +nm-rdblclk+ -6)
(defconstant +nm-setfocus+ -7)
(defconstant +nm-killfocus+ -8)

;;wm-seticon types
(defconstant +icon-small+ 0)
(defconstant +icon-big+ 1)

;;wm-hotkey commands
(defconstant +hotkeyf-shift+ #x01)
(defconstant +hotkeyf-control+ #x02)
(defconstant +hotkeyf-alt+ #x04)
(defconstant +hotkeyf-ext+ #x08)

;;keystroke flags
(defconstant +kf-extended+ #x0100)
(defconstant +kf-dlgmode+ #x0800)
(defconstant +kf-menumode+ #x1000)
(defconstant +kf-altdown+ #x2000)
(defconstant +kf-repeat+ #x4000)
(defconstant +kf-up+ #x8000)

;;key state masks for mouse messages
(defconstant +mk-lbutton+ #x01)
(defconstant +mk-rbutton+ #x02)
(defconstant +mk-shift+ #x04)
(defconstant +mk-control+ #x08)
(defconstant +mk-mbutton+ #x10)

;;wm-sizing codes
(defconstant +wmsz-left+ 1)
(defconstant +wmsz-right+ 2)
(defconstant +wmsz-top+ 3)
(defconstant +wmsz-topleft+ 4)
(defconstant +wmsz-topright+ 5)
(defconstant +wmsz-bottom+ 6)
(defconstant +wmsz-bottomleft+ 7)
(defconstant +wmsz-bottomright+ 8)

;;wm-hotkey modifiers
(defconstant +mod-alt+ 1)
(defconstant +mod-control+ 2)
(defconstant +mod-shift+ 4)
(defconstant +mod-win+ 8)

;;wm-print flags
(defconstant +prf-checkvisible+ #x01)
(defconstant +prf-nonclient+ #x02)
(defconstant +prf-client+ #x04)
(defconstant +prf-erasebkgnd+ #x08)
(defconstant +prf-children+ #x10)
(defconstant +prf-owned+ #x20)

;;virtual key codes
(defconstant +vk-lbutton+ #x001)
(defconstant +vk-cancel+ #x003)
(defconstant +vk-rbutton+ #x002)
(defconstant +vk-mbutton+ #x004)
(defconstant +vk-back+ #x008)
(defconstant +vk-tab+ #x009)
(defconstant +vk-clear+ #x00c)
(defconstant +vk-return+ #x00d)
(defconstant +vk-shift+ #x010)
(defconstant +vk-control+ #x011)
(defconstant +vk-menu+ #x012)
(defconstant +vk-pause+ #x013)
(defconstant +vk-capital+ #x014)
(defconstant +vk-escape+ #x01b)
(defconstant +vk-space+ #x020)
(defconstant +vk-prior+ #x021)
(defconstant +vk-pgup+ #x021)
(defconstant +vk-pgdn+ #x022)
(defconstant +vk-next+ #x022)
(defconstant +vk-end+ #x023)
(defconstant +vk-home+ #x024)
(defconstant +vk-left+ #x025)
(defconstant +vk-up+ #x026)
(defconstant +vk-right+ #x027)
(defconstant +vk-down+ #x028)
(defconstant +vk-select+ #x029)
(defconstant +vk-print+ #x02a)
(defconstant +vk-execute+ #x02b)
(defconstant +vk-snapshot+ #x02c)
(defconstant +vk-insert+ #x02d)
(defconstant +vk-delete+ #x02e)
(defconstant +vk-help+ #x02f)
(defconstant +vk-lwin+ #x05b)
(defconstant +vk-rwin+ #x05c)
(defconstant +vk-apps+ #x05d)
(defconstant +vk-numpad0+ #x060)
(defconstant +vk-numpad1+ #x061)
(defconstant +vk-numpad2+ #x062)
(defconstant +vk-numpad3+ #x063)
(defconstant +vk-numpad4+ #x064)
(defconstant +vk-numpad5+ #x065)
(defconstant +vk-numpad6+ #x066)
(defconstant +vk-numpad7+ #x067)
(defconstant +vk-numpad8+ #x068)
(defconstant +vk-numpad9+ #x069)
(defconstant +vk-multiply+ #x06a)
(defconstant +vk-add+ #x06b)
(defconstant +vk-separator+ #x06c)
(defconstant +vk-subtract+ #x06d)
(defconstant +vk-decimal+ #x06e)
(defconstant +vk-divide+ #x06f)
(defconstant +vk-f1+ #x070)
(defconstant +vk-f2+ #x071)
(defconstant +vk-f3+ #x072)
(defconstant +vk-f4+ #x073)
(defconstant +vk-f5+ #x074)
(defconstant +vk-f6+ #x075)
(defconstant +vk-f7+ #x076)
(defconstant +vk-f8+ #x077)
(defconstant +vk-f9+ #x078)
(defconstant +vk-f10+ #x079)
(defconstant +vk-f11+ #x07a)
(defconstant +vk-f12+ #x07b)
(defconstant +vk-f13+ #x07c)
(defconstant +vk-f14+ #x07d)
(defconstant +vk-f15+ #x07e)
(defconstant +vk-f16+ #x07f)
(defconstant +vk-f17+ #x080)
(defconstant +vk-f18+ #x081)
(defconstant +vk-f19+ #x082)
(defconstant +vk-f20+ #x083)
(defconstant +vk-f21+ #x084)
(defconstant +vk-f22+ #x085)
(defconstant +vk-f23+ #x086)
(defconstant +vk-f24+ #x087)
(defconstant +vk-numlock+ #x090)
(defconstant +vk-scroll+ #x091)
(defconstant +vk-lshift+ #x0a0)
(defconstant +vk-rshift+ #x0a1)
(defconstant +vk-lcontrol+ #x0a2)
(defconstant +vk-rcontrol+ #x0a3)
(defconstant +vk-lmenu+ #x0a4)
(defconstant +vk-rmenu+ #x0a5)
(defconstant +vk-attn+ #x0f6)
(defconstant +vk-crsel+ #x0f7)
(defconstant +vk-exsel+ #x0f8)
(defconstant +vk-ereof+ #x0f9)
(defconstant +vk-play+ #x0fa)
(defconstant +vk-zoom+ #x0fb)
(defconstant +vk-noname+ #x0fc)
(defconstant +vk-pa1+ #x0fd)
(defconstant +vk-oem-clear+ #x0fe)

;;accelerator flags
(defconstant +fvirtkey+ #x01)
(defconstant +fnoinvert+ #x02)
(defconstant +fshift+ #x04)
(defconstant +fcontrol+ #x08)
(defconstant +falt+ #x10)

;;getclasslong offsets
(defconstant +gcl-menuname+ -8)
(defconstant +gcl-hbrbackground+ -10)
(defconstant +gcl-hcursor+ -12)
(defconstant +gcl-hicon+ -14)
(defconstant +gcl-hmodule+ -16)
(defconstant +gcl-cbwndextra+ -18)
(defconstant +gcl-cbclsextra+ -20)
(defconstant +gcl-wndproc+ -24)
(defconstant +gcl-style+ -26)
(defconstant +gcw-atom+ -32)
(defconstant +gcl-hiconsm+ -34)

;;wndclass parameters
(defconstant +dlgwindowextra+ 30)

;;getwindowlong offsets
(defconstant +gwlp-wndproc+ -4)
(defconstant +gwlp-hinstance+ -6)
(defconstant +gwlp-hwndparent+ -8)
(defconstant +gwlp-id+ -12)
(defconstant +gwlp-style+ -16)
(defconstant +gwlp-exstyle+ -20)
(defconstant +gwlp-userdata+ -21)
(defconstant +dwlp-msgresult+ 0)
(defconstant +dwlp-dlgproc+ 8)
(defconstant +dwlp-user+ 16)

;;getsystemmetrics codes
(defconstant +sm-cxscreen+ 0)
(defconstant +sm-cyscreen+ 1)
(defconstant +sm-cxvscroll+ 2)
(defconstant +sm-cyhscroll+ 3)
(defconstant +sm-cycaption+ 4)
(defconstant +sm-cxborder+ 5)
(defconstant +sm-cyborder+ 6)
(defconstant +sm-cxdlgframe+ 7)
(defconstant +sm-cydlgframe+ 8)
(defconstant +sm-cyvthumb+ 9)
(defconstant +sm-cxhthumb+ 10)
(defconstant +sm-cxicon+ 11)
(defconstant +sm-cyicon+ 12)
(defconstant +sm-cxcursor+ 13)
(defconstant +sm-cycursor+ 14)
(defconstant +sm-cymenu+ 15)
(defconstant +sm-cxfullscreen+ 16)
(defconstant +sm-cyfullscreen+ 17)
(defconstant +sm-cykanjiwindow+ 18)
(defconstant +sm-mousepresent+ 19)
(defconstant +sm-cyvscroll+ 20)
(defconstant +sm-cxhscroll+ 21)
(defconstant +sm-debug+ 22)
(defconstant +sm-swapbutton+ 23)
(defconstant +sm-reserved1+ 24)
(defconstant +sm-reserved2+ 25)
(defconstant +sm-reserved3+ 26)
(defconstant +sm-reserved4+ 27)
(defconstant +sm-cxmin+ 28)
(defconstant +sm-cymin+ 29)
(defconstant +sm-cxsize+ 30)
(defconstant +sm-cysize+ 31)
(defconstant +sm-cxframe+ 32)
(defconstant +sm-cyframe+ 33)
(defconstant +sm-cxmintrack+ 34)
(defconstant +sm-cymintrack+ 35)
(defconstant +sm-cxdoubleclk+ 36)
(defconstant +sm-cydoubleclk+ 37)
(defconstant +sm-cxiconspacing+ 38)
(defconstant +sm-cyiconspacing+ 39)
(defconstant +sm-menudropalignment+ 40)
(defconstant +sm-penwindows+ 41)
(defconstant +sm-dbcsenabled+ 42)
(defconstant +sm-cmousebuttons+ 43)
(defconstant +sm-cxfixedframe+ +sm-cxdlgframe+)
(defconstant +sm-cyfixedframe+ +sm-cydlgframe+)
(defconstant +sm-cxsizeframe+ +sm-cxframe+)
(defconstant +sm-cysizeframe+ +sm-cyframe+)
(defconstant +sm-secure+ 44)
(defconstant +sm-cxedge+ 45)
(defconstant +sm-cyedge+ 46)
(defconstant +sm-cxminspacing+ 47)
(defconstant +sm-cyminspacing+ 48)
(defconstant +sm-cxsmicon+ 49)
(defconstant +sm-cysmicon+ 50)
(defconstant +sm-cysmcaption+ 51)
(defconstant +sm-cxsmsize+ 52)
(defconstant +sm-cysmsize+ 53)
(defconstant +sm-cxmenusize+ 54)
(defconstant +sm-cymenusize+ 55)
(defconstant +sm-arrange+ 56)
(defconstant +sm-cxminimized+ 57)
(defconstant +sm-cyminimized+ 58)
(defconstant +sm-cxmaxtrack+ 59)
(defconstant +sm-cymaxtrack+ 60)
(defconstant +sm-cxmaximized+ 61)
(defconstant +sm-cymaximized+ 62)
(defconstant +sm-network+ 63)
(defconstant +sm-cleanboot+ 67)
(defconstant +sm-cxdrag+ 68)
(defconstant +sm-cydrag+ 69)
(defconstant +sm-showsounds+ 70)
(defconstant +sm-cxmenucheck+ 71)
(defconstant +sm-cymenucheck+ 72)
(defconstant +sm-slowmachine+ 73)
(defconstant +sm-mideastenabled+ 74)
(defconstant +sm-mousewheelpresent+ 75)
(defconstant +sm-cmetrics+ 76)

;;predefined cursor identifiers
(defconstant +idc-arrow+ 32512)
(defconstant +idc-ibeam+ 32513)
(defconstant +idc-wait+ 32514)
(defconstant +idc-cross+ 32515)
(defconstant +idc-uparrow+ 32516)
(defconstant +idc-size+ 32640)
(defconstant +idc-icon+ 32641)
(defconstant +idc-sizenwse+ 32642)
(defconstant +idc-sizenesw+ 32643)
(defconstant +idc-sizewe+ 32644)
(defconstant +idc-sizens+ 32645)
(defconstant +idc-no+ 32648)
(defconstant +idc-hand+ 32649)
(defconstant +idc-appstarting+ 32650)
(defconstant +idc-help+ 32651)

;;predefined icon identifiers
(defconstant +idi-application+ 32512)
(defconstant +idi-hand+ 32513)
(defconstant +idi-question+ 32514)
(defconstant +idi-exclamation+ 32515)
(defconstant +idi-asterisk+ 32516)
(defconstant +idi-winlogo+ 32517)

;;system colors
(defconstant +color-scrollbar+ 0)
(defconstant +color-background+ 1)
(defconstant +color-activecaption+ 2)
(defconstant +color-inactivecaption+ 3)
(defconstant +color-menu+ 4)
(defconstant +color-window+ 5)
(defconstant +color-windowframe+ 6)
(defconstant +color-menutext+ 7)
(defconstant +color-windowtext+ 8)
(defconstant +color-captiontext+ 9)
(defconstant +color-activeborder+ 10)
(defconstant +color-inactiveborder+ 11)
(defconstant +color-appworkspace+ 12)
(defconstant +color-highlight+ 13)
(defconstant +color-highlighttext+ 14)
(defconstant +color-btnface+ 15)
(defconstant +color-btnshadow+ 16)
(defconstant +color-graytext+ 17)
(defconstant +color-btntext+ 18)
(defconstant +color-inactivecaptiontext+ 19)
(defconstant +color-btnhighlight+ 20)
(defconstant +color-3ddkshadow+ 21)
(defconstant +color-3dlight+ 22)
(defconstant +color-infotext+ 23)
(defconstant +color-infobk+ 24)
(defconstant +color-hotlight+ 26)
(defconstant +color-gradientactivecaption+ 27)
(defconstant +color-gradientinactivecaption+ 28)

;;button messages
(defconstant +bm-getcheck+ #x00f0)
(defconstant +bm-setcheck+ #x00f1)
(defconstant +bm-getstate+ #x00f2)
(defconstant +bm-setstate+ #x00f3)
(defconstant +bm-setstyle+ #x00f4)
(defconstant +bm-click+ #x00f5)
(defconstant +bm-getimage+ #x00f6)
(defconstant +bm-setimage+ #x00f7)

;;button notifications
(defconstant +bn-clicked+ 0)
(defconstant +bn-paint+ 1)
(defconstant +bn-hilite+ 2)
(defconstant +bn-unhilite+ 3)
(defconstant +bn-disable+ 4)
(defconstant +bn-doubleclicked+ 5)
(defconstant +bn-setfocus+ 6)
(defconstant +bn-killfocus+ 7)
(defconstant +bn-pushed+ +bn-hilite+)
(defconstant +bn-unpushed+ +bn-unhilite+)
(defconstant +bn-dblclk+ +bn-doubleclicked+)

;;button styles
(defconstant +bs-pushbutton+ #x0000)
(defconstant +bs-defpushbutton+ #x0001)
(defconstant +bs-checkbox+ #x0002)
(defconstant +bs-autocheckbox+ #x0003)
(defconstant +bs-radiobutton+ #x0004)
(defconstant +bs-3state+ #x0005)
(defconstant +bs-auto3state+ #x0006)
(defconstant +bs-groupbox+ #x0007)
(defconstant +bs-userbutton+ #x0008)
(defconstant +bs-autoradiobutton+ #x0009)
(defconstant +bs-ownerdraw+ #x000b)
(defconstant +bs-text+ #x0000)
(defconstant +bs-lefttext+ #x0020)
(defconstant +bs-rightbutton+ +bs-lefttext+)
(defconstant +bs-icon+ #x0040)
(defconstant +bs-bitmap+ #x0080)
(defconstant +bs-left+ #x0100)
(defconstant +bs-right+ #x0200)
(defconstant +bs-center+ #x0300)
(defconstant +bs-top+ #x0400)
(defconstant +bs-bottom+ #x0800)
(defconstant +bs-vcenter+ #x0c00)
(defconstant +bs-pushlike+ #x1000)
(defconstant +bs-multiline+ #x2000)
(defconstant +bs-notify+ #x4000)
(defconstant +bs-flat+ #x8000)

;;button states
(defconstant +bst-unchecked+ 0)
(defconstant +bst-checked+ 1)
(defconstant +bst-indeterminate+ 2)
(defconstant +bst-pushed+ 4)
(defconstant +bst-focus+ 8)

;;list box messages
(defconstant +lb-addstring+ #x0180)
(defconstant +lb-insertstring+ #x0181)
(defconstant +lb-deletestring+ #x0182)
(defconstant +lb-selitemrangeex+ #x0183)
(defconstant +lb-resetcontent+ #x0184)
(defconstant +lb-setsel+ #x0185)
(defconstant +lb-setcursel+ #x0186)
(defconstant +lb-getsel+ #x0187)
(defconstant +lb-getcursel+ #x0188)
(defconstant +lb-gettext+ #x0189)
(defconstant +lb-gettextlen+ #x018a)
(defconstant +lb-getcount+ #x018b)
(defconstant +lb-selectstring+ #x018c)
(defconstant +lb-dir+ #x018d)
(defconstant +lb-gettopindex+ #x018e)
(defconstant +lb-findstring+ #x018f)
(defconstant +lb-getselcount+ #x0190)
(defconstant +lb-getselitems+ #x0191)
(defconstant +lb-settabstops+ #x0192)
(defconstant +lb-gethorizontalextent+ #x0193)
(defconstant +lb-sethorizontalextent+ #x0194)
(defconstant +lb-setcolumnwidth+ #x0195)
(defconstant +lb-addfile+ #x0196)
(defconstant +lb-settopindex+ #x0197)
(defconstant +lb-getitemrect+ #x0198)
(defconstant +lb-getitemdata+ #x0199)
(defconstant +lb-setitemdata+ #x019a)
(defconstant +lb-selitemrange+ #x019b)
(defconstant +lb-setanchorindex+ #x019c)
(defconstant +lb-getanchorindex+ #x019d)
(defconstant +lb-setcaretindex+ #x019e)
(defconstant +lb-getcaretindex+ #x019f)
(defconstant +lb-setitemheight+ #x01a0)
(defconstant +lb-getitemheight+ #x01a1)
(defconstant +lb-findstringexact+ #x01a2)
(defconstant +lb-setlocale+ #x01a5)
(defconstant +lb-getlocale+ #x01a6)
(defconstant +lb-setcount+ #x01a7)
(defconstant +lb-initstorage+ #x01a8)
(defconstant +lb-itemfrompoint+ #x01a9)

;;list box notifications
(defconstant +lbn-errspace+ -2)
(defconstant +lbn-selchange+ 1)
(defconstant +lbn-dblclk+ 2)
(defconstant +lbn-selcancel+ 3)
(defconstant +lbn-setfocus+ 4)
(defconstant +lbn-killfocus+ 5)

;;list box styles
(defconstant +lbs-notify+ #x0001)
(defconstant +lbs-sort+ #x0002)
(defconstant +lbs-noredraw+ #x0004)
(defconstant +lbs-multiplesel+ #x0008)
(defconstant +lbs-ownerdrawfixed+ #x0010)
(defconstant +lbs-ownerdrawvariable+ #x0020)
(defconstant +lbs-hasstrings+ #x0040)
(defconstant +lbs-usetabstops+ #x0080)
(defconstant +lbs-nointegralheight+ #x0100)
(defconstant +lbs-multicolumn+ #x0200)
(defconstant +lbs-wantkeyboardinput+ #x0400)
(defconstant +lbs-extendedsel+ #x0800)
(defconstant +lbs-disablenoscroll+ #x1000)
(defconstant +lbs-nodata+ #x2000)
(defconstant +lbs-nosel+ #x4000)
(defconstant +lbs-standard+ (+ +lbs-notify+ +lbs-sort+ +ws-vscroll+ +ws-border+))

;;list box return values
(defconstant +lb-okay+ 0)
(defconstant +lb-err+ -1)
(defconstant +lb-errspace+ -2)

;;combo box messages
(defconstant +cb-geteditsel+ #x0140)
(defconstant +cb-limittext+ #x0141)
(defconstant +cb-seteditsel+ #x0142)
(defconstant +cb-addstring+ #x0143)
(defconstant +cb-deletestring+ #x0144)
(defconstant +cb-dir+ #x0145)
(defconstant +cb-getcount+ #x0146)
(defconstant +cb-getcursel+ #x0147)
(defconstant +cb-getlbtext+ #x0148)
(defconstant +cb-getlbtextlen+ #x0149)
(defconstant +cb-insertstring+ #x014a)
(defconstant +cb-resetcontent+ #x014b)
(defconstant +cb-findstring+ #x014c)
(defconstant +cb-selectstring+ #x014d)
(defconstant +cb-setcursel+ #x014e)
(defconstant +cb-showdropdown+ #x014f)
(defconstant +cb-getitemdata+ #x0150)
(defconstant +cb-setitemdata+ #x0151)
(defconstant +cb-getdroppedcontrolrect+ #x0152)
(defconstant +cb-setitemheight+ #x0153)
(defconstant +cb-getitemheight+ #x0154)
(defconstant +cb-setextendedui+ #x0155)
(defconstant +cb-getextendedui+ #x0156)
(defconstant +cb-getdroppedstate+ #x0157)
(defconstant +cb-findstringexact+ #x0158)
(defconstant +cb-setlocale+ #x0159)
(defconstant +cb-getlocale+ #x015a)
(defconstant +cb-gettopindex+ #x015b)
(defconstant +cb-settopindex+ #x015c)
(defconstant +cb-gethorizontalextent+ #x015d)
(defconstant +cb-sethorizontalextent+ #x015e)
(defconstant +cb-getdroppedwidth+ #x015f)
(defconstant +cb-setdroppedwidth+ #x0160)
(defconstant +cb-initstorage+ #x0161)

;;combo box notifications
(defconstant +cbn-errspace+ -1)
(defconstant +cbn-selchange+ 1)
(defconstant +cbn-dblclk+ 2)
(defconstant +cbn-setfocus+ 3)
(defconstant +cbn-killfocus+ 4)
(defconstant +cbn-editchange+ 5)
(defconstant +cbn-editupdate+ 6)
(defconstant +cbn-dropdown+ 7)
(defconstant +cbn-closeup+ 8)
(defconstant +cbn-selendok+ 9)
(defconstant +cbn-selendcancel+ 10)

;;combo box styles
(defconstant +cbs-simple+ #x0001)
(defconstant +cbs-dropdown+ #x0002)
(defconstant +cbs-dropdownlist+ #x0003)
(defconstant +cbs-ownerdrawfixed+ #x0010)
(defconstant +cbs-ownerdrawvariable+ #x0020)
(defconstant +cbs-autohscroll+ #x0040)
(defconstant +cbs-oemconvert+ #x0080)
(defconstant +cbs-sort+ #x0100)
(defconstant +cbs-hasstrings+ #x0200)
(defconstant +cbs-nointegralheight+ #x0400)
(defconstant +cbs-disablenoscroll+ #x0800)
(defconstant +cbs-uppercase+ #x2000)
(defconstant +cbs-lowercase+ #x4000)

;;combo box return values
(defconstant +cb-okay+ 0)
(defconstant +cb-err+ -1)
(defconstant +cb-errspace+ -2)

;;edit control messages
(defconstant +em-getsel+ #x00b0)
(defconstant +em-setsel+ #x00b1)
(defconstant +em-getrect+ #x00b2)
(defconstant +em-setrect+ #x00b3)
(defconstant +em-setrectnp+ #x00b4)
(defconstant +em-scroll+ #x00b5)
(defconstant +em-linescroll+ #x00b6)
(defconstant +em-scrollcaret+ #x00b7)
(defconstant +em-getmodify+ #x00b8)
(defconstant +em-setmodify+ #x00b9)
(defconstant +em-getlinecount+ #x00ba)
(defconstant +em-lineindex+ #x00bb)
(defconstant +em-sethandle+ #x00bc)
(defconstant +em-gethandle+ #x00bd)
(defconstant +em-getthumb+ #x00be)
(defconstant +em-linelength+ #x00c1)
(defconstant +em-replacesel+ #x00c2)
(defconstant +em-getline+ #x00c4)
(defconstant +em-limittext+ #x00c5)
(defconstant +em-canundo+ #x00c6)
(defconstant +em-undo+ #x00c7)
(defconstant +em-fmtlines+ #x00c8)
(defconstant +em-linefromchar+ #x00c9)
(defconstant +em-settabstops+ #x00cb)
(defconstant +em-setpasswordchar+ #x00cc)
(defconstant +em-emptyundobuffer+ #x00cd)
(defconstant +em-getfirstvisibleline+ #x00ce)
(defconstant +em-setreadonly+ #x00cf)
(defconstant +em-setwordbreakproc+ #x00d0)
(defconstant +em-getwordbreakproc+ #x00d1)
(defconstant +em-getpasswordchar+ #x00d2)
(defconstant +em-setmargins+ #x00d3)
(defconstant +em-getmargins+ #x00d4)
(defconstant +em-setlimittext+ +em-limittext+)
(defconstant +em-getlimittext+ #x00d5)
(defconstant +em-posfromchar+ #x00d6)
(defconstant +em-charfrompos+ #x00d7)

;;edit control em-setmargin parameters
(defconstant +ec-leftmargin+ 1)
(defconstant +ec-rightmargin+ 2)
(defconstant +ec-usefontinfo+ #x0ffff)

;;edit control notifications
(defconstant +en-setfocus+ #x0100)
(defconstant +en-killfocus+ #x0200)
(defconstant +en-change+ #x0300)
(defconstant +en-update+ #x0400)
(defconstant +en-errspace+ #x0500)
(defconstant +en-maxtext+ #x0501)
(defconstant +en-hscroll+ #x0601)
(defconstant +en-vscroll+ #x0602)

;;edit control styles
(defconstant +es-left+ #x0000)
(defconstant +es-center+ #x0001)
(defconstant +es-right+ #x0002)
(defconstant +es-multiline+ #x0004)
(defconstant +es-uppercase+ #x0008)
(defconstant +es-lowercase+ #x0010)
(defconstant +es-password+ #x0020)
(defconstant +es-autovscroll+ #x0040)
(defconstant +es-autohscroll+ #x0080)
(defconstant +es-nohidesel+ #x0100)
(defconstant +es-oemconvert+ #x0400)
(defconstant +es-readonly+ #x0800)
(defconstant +es-wantreturn+ #x1000)
(defconstant +es-number+ #x2000)

;;static window messages
(defconstant +stm-seticon+ #x0170)
(defconstant +stm-geticon+ #x0171)
(defconstant +stm-setimage+ #x0172)
(defconstant +stm-getimage+ #x0173)

;;static window notifications
(defconstant +stn-clicked+ 0)
(defconstant +stn-dblclk+ 1)
(defconstant +stn-enable+ 2)
(defconstant +stn-disable+ 3)

;;static window styles
(defconstant +ss-left+ #x0000)
(defconstant +ss-center+ #x0001)
(defconstant +ss-right+ #x0002)
(defconstant +ss-icon+ #x0003)
(defconstant +ss-blackrect+ #x0004)
(defconstant +ss-grayrect+ #x0005)
(defconstant +ss-whiterect+ #x0006)
(defconstant +ss-blackframe+ #x0007)
(defconstant +ss-grayframe+ #x0008)
(defconstant +ss-whiteframe+ #x0009)
(defconstant +ss-useritem+ #x000a)
(defconstant +ss-simple+ #x000b)
(defconstant +ss-leftnowordwrap+ #x000c)
(defconstant +ss-bitmap+ #x000e)
(defconstant +ss-ownerdraw+ #x000d)
(defconstant +ss-enhmetafile+ #x000f)
(defconstant +ss-etchedhorz+ #x0010)
(defconstant +ss-etchedvert+ #x0011)
(defconstant +ss-etchedframe+ #x0012)
(defconstant +ss-typemask+ #x001f)
(defconstant +ss-noprefix+ #x0080)
(defconstant +ss-notify+ #x0100)
(defconstant +ss-centerimage+ #x0200)
(defconstant +ss-rightjust+ #x0400)
(defconstant +ss-realsizeimage+ #x0800)
(defconstant +ss-sunken+ #x1000)

;;scroll bar constants
(defconstant +sb-horz+ 0)
(defconstant +sb-vert+ 1)
(defconstant +sb-ctl+ 2)
(defconstant +sb-both+ 3)

;;scroll bar messages
(defconstant +sbm-setpos+ #x00e0)
(defconstant +sbm-getpos+ #x00e1)
(defconstant +sbm-setrange+ #x00e2)
(defconstant +sbm-setrangeredraw+ #x00e6)
(defconstant +sbm-getrange+ #x00e3)
(defconstant +sbm-enable-arrows+ #x00e4)
(defconstant +sbm-setscrollinfo+ #x00e9)
(defconstant +sbm-getscrollinfo+ #x00ea)

;;scroll bar commands
(defconstant +sb-lineup+ 0)
(defconstant +sb-lineleft+ 0)
(defconstant +sb-linedown+ 1)
(defconstant +sb-lineright+ 1)
(defconstant +sb-pageup+ 2)
(defconstant +sb-pageleft+ 2)
(defconstant +sb-pagedown+ 3)
(defconstant +sb-pageright+ 3)
(defconstant +sb-thumbposition+ 4)
(defconstant +sb-thumbtrack+ 5)
(defconstant +sb-top+ 6)
(defconstant +sb-left+ 6)
(defconstant +sb-bottom+ 7)
(defconstant +sb-right+ 7)
(defconstant +sb-endscroll+ 8)

;;scroll bar styles
(defconstant +sbs-horz+ #x0000)
(defconstant +sbs-vert+ #x0001)
(defconstant +sbs-topalign+ #x0002)
(defconstant +sbs-leftalign+ #x0002)
(defconstant +sbs-bottomalign+ #x0004)
(defconstant +sbs-rightalign+ #x0004)
(defconstant +sbs-sizeboxtopleftalign+ #x0002)
(defconstant +sbs-sizeboxbottomrightalign+ #x0004)
(defconstant +sbs-sizebox+ #x0008)
(defconstant +sbs-sizegrip+ #x0010)

;;scroll bar info flags
(defconstant +sif-range+ #x0001)
(defconstant +sif-page+ #x0002)
(defconstant +sif-pos+ #x0004)
(defconstant +sif-disablenoscroll+ #x0008)
(defconstant +sif-trackpos+ #x0010)
(defconstant +sif-all+ (+ +sif-range+ +sif-page+ +sif-pos+ +sif-trackpos+))

;;dialog styles
(defconstant +ds-absalign+ #x0001)
(defconstant +ds-sysmodal+ #x0002)
(defconstant +ds-3dlook+ #x0004)
(defconstant +ds-fixedsys+ #x0008)
(defconstant +ds-nofailcreate+ #x0010)
(defconstant +ds-localedit+ #x0020)
(defconstant +ds-setfont+ #x0040)
(defconstant +ds-modalframe+ #x0080)
(defconstant +ds-noidlemsg+ #x0100)
(defconstant +ds-setforeground+ #x0200)
(defconstant +ds-control+ #x0400)
(defconstant +ds-center+ #x0800)
(defconstant +ds-centermouse+ #x1000)
(defconstant +ds-contexthelp+ #x2000)

;;dialog codes
(defconstant +dlgc-wantarrows+ #x0001)
(defconstant +dlgc-wanttab+ #x0002)
(defconstant +dlgc-wantallkeys+ #x0004)
(defconstant +dlgc-wantmessage+ #x0004)
(defconstant +dlgc-hassetsel+ #x0008)
(defconstant +dlgc-defpushbutton+ #x0010)
(defconstant +dlgc-undefpushbutton+ #x0020)
(defconstant +dlgc-radiobutton+ #x0040)
(defconstant +dlgc-wantchars+ #x0080)
(defconstant +dlgc-static+ #x0100)
(defconstant +dlgc-button+ #x2000)

;;menu flags
(defconstant +mf-insert+ #x0000)
(defconstant +mf-change+ #x0080)
(defconstant +mf-append+ #x0100)
(defconstant +mf-delete+ #x0200)
(defconstant +mf-remove+ #x1000)
(defconstant +mf-bycommand+ #x0000)
(defconstant +mf-byposition+ #x0400)
(defconstant +mf-separator+ #x0800)
(defconstant +mf-unchecked+ #x0000)
(defconstant +mf-enabled+ #x0000)
(defconstant +mf-grayed+ #x0001)
(defconstant +mf-disabled+ #x0002)
(defconstant +mf-checked+ #x0008)
(defconstant +mf-usecheckbitmaps+ #x0200)
(defconstant +mf-string+ #x0000)
(defconstant +mf-bitmap+ #x0004)
(defconstant +mf-ownerdraw+ #x0100)
(defconstant +mf-popup+ #x0010)
(defconstant +mf-menubarbreak+ #x0020)
(defconstant +mf-menubreak+ #x0040)
(defconstant +mf-unhilite+ #x0000)
(defconstant +mf-hilite+ #x0080)
(defconstant +mf-default+ #x1000)
(defconstant +mf-sysmenu+ #x2000)
(defconstant +mf-help+ #x4000)
(defconstant +mf-rightjustify+ #x4000)
(defconstant +mf-mouseselect+ #x8000)
(defconstant +mf-end+ #x0080)
(defconstant +mft-string+ +mf-string+)
(defconstant +mft-bitmap+ +mf-bitmap+)
(defconstant +mft-menubarbreak+ +mf-menubarbreak+)
(defconstant +mft-menubreak+ +mf-menubreak+)
(defconstant +mft-ownerdraw+ +mf-ownerdraw+)
(defconstant +mft-radiocheck+ #x0200)
(defconstant +mft-separator+ +mf-separator+)
(defconstant +mft-rightorder+ #x2000)
(defconstant +mft-rightjustify+ +mf-rightjustify+)
(defconstant +mfs-grayed+ #x0003)
(defconstant +mfs-disabled+ +mfs-grayed+)
(defconstant +mfs-checked+ +mf-checked+)
(defconstant +mfs-hilite+ +mf-hilite+)
(defconstant +mfs-enabled+ +mf-enabled+)
(defconstant +mfs-unchecked+ +mf-unchecked+)
(defconstant +mfs-unhilite+ +mf-unhilite+)
(defconstant +mfs-default+ +mf-default+)
(defconstant +mfr-popup+ #x0001)
(defconstant +mfr-end+ +mf-end+)

;;system menu command values
(defconstant +sc-size+ 61440)
(defconstant +sc-move+ 61456)
(defconstant +sc-minimize+ 61472)
(defconstant +sc-maximize+ 61488)
(defconstant +sc-nextwindow+ 61504)
(defconstant +sc-prevwindow+ 61520)
(defconstant +sc-close+ 61536)
(defconstant +sc-vscroll+ 61552)
(defconstant +sc-hscroll+ 61568)
(defconstant +sc-mousemenu+ 61584)
(defconstant +sc-keymenu+ 61696)
(defconstant +sc-arrange+ 61712)
(defconstant +sc-restore+ 61728)
(defconstant +sc-tasklist+ 61744)
(defconstant +sc-screensave+ 61760)
(defconstant +sc-hotkey+ 61776)
(defconstant +sc-default+ 61792)
(defconstant +sc-monitorpower+ 61808)
(defconstant +sc-contexthelp+ 61824)
(defconstant +sc-separator+ 61455)

;;border types
(defconstant +bdr-raisedouter+ #x01)
(defconstant +bdr-sunkenouter+ #x02)
(defconstant +bdr-raisedinner+ #x04)
(defconstant +bdr-sunkeninner+ #x08)
(defconstant +bdr-outer+ #x03)
(defconstant +bdr-inner+ #x0c)
(defconstant +bdr-raised+ #x05)
(defconstant +bdr-sunken+ #x0a)
(defconstant +edge-raised+ (+ +bdr-raisedouter+ +bdr-raisedinner+))
(defconstant +edge-sunken+ (+ +bdr-sunkenouter+ +bdr-sunkeninner+))
(defconstant +edge-etched+ (+ +bdr-sunkenouter+ +bdr-raisedinner+))
(defconstant +edge-bump+ (+ +bdr-raisedouter+ +bdr-sunkeninner+))

;;border flags
(defconstant +bf-left+ #x0001)
(defconstant +bf-top+ #x0002)
(defconstant +bf-right+ #x0004)
(defconstant +bf-bottom+ #x0008)
(defconstant +bf-topleft+ (+ +bf-top+ +bf-left+))
(defconstant +bf-topright+ (+ +bf-top+ +bf-right+))
(defconstant +bf-bottomleft+ (+ +bf-bottom+ +bf-left+))
(defconstant +bf-bottomright+ (+ +bf-bottom+ +bf-right+))
(defconstant +bf-rect+ (+ +bf-left+ +bf-top+ +bf-right+ +bf-bottom+))
(defconstant +bf-diagonal+ #x0010)
(defconstant +bf-diagonal-endtopright+ (+ +bf-diagonal+ +bf-top+ +bf-right+))
(defconstant +bf-diagonal-endtopleft+ (+ +bf-diagonal+ +bf-top+ +bf-left+))
(defconstant +bf-diagonal-endbottomleft+ (+ +bf-diagonal+ +bf-bottom+ +bf-left+))
(defconstant +bf-diagonal-endbottomright+ (+ +bf-diagonal+ +bf-bottom+ +bf-right+))
(defconstant +bf-middle+ #x0800)
(defconstant +bf-soft+ #x1000)
(defconstant +bf-adjust+ #x2000)
(defconstant +bf-flat+ #x4000)
(defconstant +bf-mono+ #x8000)

;;frame control types
(defconstant +dfc-caption+ 1)
(defconstant +dfc-menu+ 2)
(defconstant +dfc-scroll+ 3)
(defconstant +dfc-button+ 4)
(defconstant +dfc-popupmenu+ 5)

;;frame control states
(defconstant +dfcs-captionclose+ #x0000)
(defconstant +dfcs-captionmin+ #x0001)
(defconstant +dfcs-captionmax+ #x0002)
(defconstant +dfcs-captionrestore+ #x0003)
(defconstant +dfcs-captionhelp+ #x0004)
(defconstant +dfcs-menuarrow+ #x0000)
(defconstant +dfcs-menucheck+ #x0001)
(defconstant +dfcs-menubullet+ #x0002)
(defconstant +dfcs-menuarrowright+ #x0004)
(defconstant +dfcs-scrollup+ #x0000)
(defconstant +dfcs-scrolldown+ #x0001)
(defconstant +dfcs-scrollleft+ #x0002)
(defconstant +dfcs-scrollright+ #x0003)
(defconstant +dfcs-scrollcombobox+ #x0005)
(defconstant +dfcs-scrollsizegrip+ #x0008)
(defconstant +dfcs-scrollsizegripright+ #x0010)
(defconstant +dfcs-buttoncheck+ #x0000)
(defconstant +dfcs-buttonradioimage+ #x0001)
(defconstant +dfcs-buttonradiomask+ #x0002)
(defconstant +dfcs-buttonradio+ #x0004)
(defconstant +dfcs-button3state+ #x0008)
(defconstant +dfcs-buttonpush+ #x0010)
(defconstant +dfcs-inactive+ #x0100)
(defconstant +dfcs-pushed+ #x0200)
(defconstant +dfcs-checked+ #x0400)
(defconstant +dfcs-transparent+ #x0800)
(defconstant +dfcs-hot+ #x1000)
(defconstant +dfcs-adjustrect+ #x2000)
(defconstant +dfcs-flat+ #x4000)
(defconstant +dfcs-mono+ #x8000)

;;drawcaption flags
(defconstant +dc-active+ #x01)
(defconstant +dc-smallcap+ #x02)
(defconstant +dc-icon+ #x04)
(defconstant +dc-text+ #x08)
(defconstant +dc-inbutton+ #x10)

;;drawiconex options
(defconstant +di-mask+ 1)
(defconstant +di-image+ 2)
(defconstant +di-normal+ 3)
(defconstant +di-compat+ 4)
(defconstant +di-defaultsize+ 8)

;;drawtext parameters
(defconstant +dt-top+ #x00000)
(defconstant +dt-left+ #x00000)
(defconstant +dt-center+ #x00001)
(defconstant +dt-right+ #x00002)
(defconstant +dt-vcenter+ #x00004)
(defconstant +dt-bottom+ #x00008)
(defconstant +dt-wordbreak+ #x00010)
(defconstant +dt-singleline+ #x00020)
(defconstant +dt-expandtabs+ #x00040)
(defconstant +dt-tabstop+ #x00080)
(defconstant +dt-noclip+ #x00100)
(defconstant +dt-externalleading+ #x00200)
(defconstant +dt-calcrect+ #x00400)
(defconstant +dt-noprefix+ #x00800)
(defconstant +dt-internal+ #x01000)
(defconstant +dt-editcontrol+ #x02000)
(defconstant +dt-path-ellipsis+ #x04000)
(defconstant +dt-end-ellipsis+ #x08000)
(defconstant +dt-modifystring+ #x10000)
(defconstant +dt-rtlreading+ #x20000)
(defconstant +dt-word-ellipsis+ #x40000)

;;getdcex flags
(defconstant +dcx-window+ #x000001)
(defconstant +dcx-cache+ #x000002)
(defconstant +dcx-noresetattrs+ #x000004)
(defconstant +dcx-clipchildren+ #x000008)
(defconstant +dcx-clipsiblings+ #x000010)
(defconstant +dcx-parentclip+ #x000020)
(defconstant +dcx-excludergn+ #x000040)
(defconstant +dcx-intersectrgn+ #x000080)
(defconstant +dcx-excludeupdate+ #x000100)
(defconstant +dcx-intersectupdate+ #x000200)
(defconstant +dcx-lockwindowupdate+ #x000400)
(defconstant +dcx-validate+ #x200000)

;;setwindowshook codes
(defconstant +wh-msgfilter+ -1)
(defconstant +wh-journalrecord+ 0)
(defconstant +wh-journalplayback+ 1)
(defconstant +wh-keyboard+ 2)
(defconstant +wh-getmessage+ 3)
(defconstant +wh-callwndproc+ 4)
(defconstant +wh-cbt+ 5)
(defconstant +wh-sysmsgfilter+ 6)
(defconstant +wh-mouse+ 7)
(defconstant +wh-hardware+ 8)
(defconstant +wh-debug+ 9)
(defconstant +wh-shell+ 10)
(defconstant +wh-foregroundidle+ 11)
(defconstant +wh-callwndprocret+ 12)
(defconstant +wh-keyboard-ll+ 13)
(defconstant +wh-mouse-ll+ 14)

;;hook codes
(defconstant +hc-action+ 0)
(defconstant +hc-getnext+ 1)
(defconstant +hc-skip+ 2)
(defconstant +hc-noremove+ 3)
(defconstant +hc-sysmodalon+ 4)
(defconstant +hc-sysmodaloff+ 5)

;;cbt hook codes
(defconstant +hcbt-movesize+ 0)
(defconstant +hcbt-minmax+ 1)
(defconstant +hcbt-qs+ 2)
(defconstant +hcbt-createwnd+ 3)
(defconstant +hcbt-destroywnd+ 4)
(defconstant +hcbt-activate+ 5)
(defconstant +hcbt-clickskipped+ 6)
(defconstant +hcbt-keyskipped+ 7)
(defconstant +hcbt-syscommand+ 8)
(defconstant +hcbt-setfocus+ 9)

;;exitwindowsex flags
(defconstant +ewx-logoff+ 0)
(defconstant +ewx-shutdown+ 1)
(defconstant +ewx-reboot+ 2)
(defconstant +ewx-force+ 4)
(defconstant +ewx-poweroff+ 8)

;;winhelp commands
(defconstant +help-context+ #x001)
(defconstant +help-quit+ #x002)
(defconstant +help-index+ #x003)
(defconstant +help-contents+ #x003)
(defconstant +help-helponhelp+ #x004)
(defconstant +help-setindex+ #x005)
(defconstant +help-setcontents+ #x005)
(defconstant +help-contextpopup+ #x008)
(defconstant +help-forcefile+ #x009)
(defconstant +help-contextmenu+ #x00a)
(defconstant +help-finder+ #x00b)
(defconstant +help-wm-help+ #x00c)
(defconstant +help-setpopup-pos+ #x00d)
(defconstant +help-key+ #x101)
(defconstant +help-command+ #x102)
(defconstant +help-partialkey+ #x105)
(defconstant +help-multikey+ #x201)
(defconstant +help-setwinpos+ #x203)

;;keybd-event flags
(defconstant +keyeventf-extendedkey+ #x1)
(defconstant +keyeventf-keyup+ #x2)

;;mouse-event flags
(defconstant +mouseeventf-move+ #x0001)
(defconstant +mouseeventf-leftdown+ #x0002)
(defconstant +mouseeventf-leftup+ #x0004)
(defconstant +mouseeventf-rightdown+ #x0008)
(defconstant +mouseeventf-rightup+ #x0010)
(defconstant +mouseeventf-middledown+ #x0020)
(defconstant +mouseeventf-middleup+ #x0040)
(defconstant +mouseeventf-wheel+ #x0800)
(defconstant +mouseeventf-absolute+ #x8000)

;;trackpopupmenu flags
(defconstant +tpm-leftbutton+ #x0000)
(defconstant +tpm-rightbutton+ #x0002)
(defconstant +tpm-leftalign+ #x0000)
(defconstant +tpm-centeralign+ #x0004)
(defconstant +tpm-rightalign+ #x0008)
(defconstant +tpm-topalign+ #x0000)
(defconstant +tpm-vcenteralign+ #x0010)
(defconstant +tpm-bottomalign+ #x0020)
(defconstant +tpm-horizontal+ #x0000)
(defconstant +tpm-vertical+ #x0040)
(defconstant +tpm-nonotify+ #x0080)
(defconstant +tpm-returncmd+ #x0100)
(defconstant +tpm-recurse+ #x0001)
(defconstant +tpm-horposanimation+ #x0400)
(defconstant +tpm-horneganimation+ #x0800)
(defconstant +tpm-verposanimation+ #x1000)
(defconstant +tpm-verneganimation+ #x2000)
(defconstant +tpm-noanimation+ #x4000)
(defconstant +tpm-layoutrtl+ #x8000)

;;menu item info mask values
(defconstant +miim-state+ #x001)
(defconstant +miim-id+ #x002)
(defconstant +miim-submenu+ #x004)
(defconstant +miim-checkmarks+ #x008)
(defconstant +miim-type+ #x010)
(defconstant +miim-data+ #x020)
(defconstant +miim-string+ #x040)
(defconstant +miim-bitmap+ #x080)
(defconstant +miim-ftype+ #x100)

;;drawitem(defcstruct control types
(defconstant +odt-menu+ 1)
(defconstant +odt-listbox+ 2)
(defconstant +odt-combobox+ 3)
(defconstant +odt-button+ 4)
(defconstant +odt-static+ 5)

;;drawitem(defcstruct actions
(defconstant +oda-drawentire+ 1)
(defconstant +oda-select+ 2)
(defconstant +oda-focus+ 4)

;;drawitem(defcstruct states
(defconstant +ods-selected+ #x0001)
(defconstant +ods-grayed+ #x0002)
(defconstant +ods-disabled+ #x0004)
(defconstant +ods-checked+ #x0008)
(defconstant +ods-focus+ #x0010)
(defconstant +ods-default+ #x0020)
(defconstant +ods-comboboxedit+ #x1000)
(defconstant +ods-hotlight+ #x0040)
(defconstant +ods-inactive+ #x0080)

;;windowplacement flags
(defconstant +wpf-setminposition+ 1)
(defconstant +wpf-restoretomaximized+ 2)

;;layered window attributes
(defconstant +lwa-colorkey+ 1)
(defconstant +lwa-alpha+ 2)

;;updatelayeredwindow flags
(defconstant +ulw-colorkey+ 1)
(defconstant +ulw-alpha+ 2)
(defconstant +ulw-opaque+ 4)

;;systemparametersinfo parameters
(defconstant +spi-getaccesstimeout+ 60)
(defconstant +spi-getanimation+ 72)
(defconstant +spi-getbeep+ 1)
(defconstant +spi-getborder+ 5)
(defconstant +spi-getdefaultinputlang+ 89)
(defconstant +spi-getdragfullwindows+ 38)
(defconstant +spi-getfasttaskswitch+ 35)
(defconstant +spi-getfilterkeys+ 50)
(defconstant +spi-getfontsmoothing+ 74)
(defconstant +spi-getgridgranularity+ 18)
(defconstant +spi-gethighcontrast+ 66)
(defconstant +spi-geticonmetrics+ 45)
(defconstant +spi-geticontitlelogfont+ 31)
(defconstant +spi-geticontitlewrap+ 25)
(defconstant +spi-getkeyboarddelay+ 22)
(defconstant +spi-getkeyboardpref+ 68)
(defconstant +spi-getkeyboardspeed+ 10)
(defconstant +spi-getlowpoweractive+ 83)
(defconstant +spi-getlowpowertimeout+ 79)
(defconstant +spi-getmenudropalignment+ 27)
(defconstant +spi-getminimizedmetrics+ 43)
(defconstant +spi-getmouse+ 3)
(defconstant +spi-getmousekeys+ 54)
(defconstant +spi-getmousetrails+ 94)
(defconstant +spi-getnonclientmetrics+ 41)
(defconstant +spi-getpoweroffactive+ 84)
(defconstant +spi-getpowerofftimeout+ 80)
(defconstant +spi-getscreenreader+ 70)
(defconstant +spi-getscreensaveactive+ 16)
(defconstant +spi-getscreensavetimeout+ 14)
(defconstant +spi-getserialkeys+ 62)
(defconstant +spi-getshowsounds+ 56)
(defconstant +spi-getsoundsentry+ 64)
(defconstant +spi-getstickykeys+ 58)
(defconstant +spi-gettogglekeys+ 52)
(defconstant +spi-getwindowsextension+ 92)
(defconstant +spi-getworkarea+ 48)
(defconstant +spi-iconhorizontalspacing+ 13)
(defconstant +spi-iconverticalspacing+ 24)
(defconstant +spi-langdriver+ 12)
(defconstant +spi-screensaverrunning+ 97)
(defconstant +spi-setaccesstimeout+ 61)
(defconstant +spi-setanimation+ 73)
(defconstant +spi-setbeep+ 2)
(defconstant +spi-setborder+ 6)
(defconstant +spi-setdefaultinputlang+ 90)
(defconstant +spi-setdeskpattern+ 21)
(defconstant +spi-setdeskwallpaper+ 20)
(defconstant +spi-setdoubleclicktime+ 32)
(defconstant +spi-setdoubleclkheight+ 30)
(defconstant +spi-setdoubleclkwidth+ 29)
(defconstant +spi-setdragfullwindows+ 37)
(defconstant +spi-setdragheight+ 77)
(defconstant +spi-setdragwidth+ 76)
(defconstant +spi-setfasttaskswitch+ 36)
(defconstant +spi-setfilterkeys+ 51)
(defconstant +spi-setfontsmoothing+ 75)
(defconstant +spi-setgridgranularity+ 19)
(defconstant +spi-sethandheld+ 78)
(defconstant +spi-sethighcontrast+ 67)
(defconstant +spi-seticonmetrics+ 46)
(defconstant +spi-seticontitlelogfont+ 34)
(defconstant +spi-seticontitlewrap+ 26)
(defconstant +spi-setkeyboarddelay+ 23)
(defconstant +spi-setkeyboardpref+ 69)
(defconstant +spi-setkeyboardspeed+ 11)
(defconstant +spi-setlangtoggle+ 91)
(defconstant +spi-setlowpoweractive+ 85)
(defconstant +spi-setlowpowertimeout+ 81)
(defconstant +spi-setmenudropalignment+ 28)
(defconstant +spi-setminimizedmetrics+ 44)
(defconstant +spi-setmouse+ 4)
(defconstant +spi-setmousebuttonswap+ 33)
(defconstant +spi-setmousekeys+ 55)
(defconstant +spi-setmousetrails+ 93)
(defconstant +spi-setnonclientmetrics+ 42)
(defconstant +spi-setpenwindows+ 49)
(defconstant +spi-setpoweroffactive+ 86)
(defconstant +spi-setpowerofftimeout+ 82)
(defconstant +spi-setscreenreader+ 71)
(defconstant +spi-setscreensaveactive+ 17)
(defconstant +spi-setscreensaverrunning+ 97)
(defconstant +spi-setscreensavetimeout+ 15)
(defconstant +spi-setserialkeys+ 63)
(defconstant +spi-setshowsounds+ 57)
(defconstant +spi-setsoundsentry+ 65)
(defconstant +spi-setstickykeys+ 59)
(defconstant +spi-settogglekeys+ 53)
(defconstant +spi-setworkarea+ 47)

;;systemparametersinfo flags
(defconstant +spif-updateinifile+ 1)
(defconstant +spif-sendwininichange+ 2)

;;gesture information flags
(defconstant +gf-begin+ 1)
(defconstant +gf-inertia+ 2)
(defconstant +gf-end+ 4)

;;gesture ids
(defconstant +gid-begin+ 1)
(defconstant +gid-end+ 2)
(defconstant +gid-zoom+ 3)
(defconstant +gid-pan+ 4)
(defconstant +gid-rotate+ 5)
(defconstant +gid-twofingertap+ 6)
(defconstant +gid-pressandtap+ 7)
(defconstant +gid-rollover+ +gid-pressandtap+)

;;zoom gesture confiration flags
(defconstant +gc-zoom+ #x00000001)

;;pan gesture configuration flags
(defconstant +gc-pan+ #x00000001)
(defconstant +gc-pan-with-single-finger-vertically+ #x00000002)
(defconstant +gc-pan-with-single-finger-horizontally+ #x00000004)
(defconstant +gc-pan-with-gutter+ #x00000008)
(defconstant +gc-pan-with-inertia+ #x00000010)

;;rotate gesture configuration flags
(defconstant +gc-rotate+ #x00000001)

;;two finger tap configuration flags
(defconstant +gc-twofingertap+ #x00000001)

;;press and tap configuration flags
(defconstant +gc-pressandtap+ #x00000001)
(defconstant +gc-rollover+ +gc-pressandtap+)
